apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: fluence-pi
  namespace: default
spec:
  scheduleTimeoutSeconds: 600
  minMember: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fluence-pi
  namespace: default
  labels:
    pod-group.scheduling.sigs.k8s.io: fluence-pi 
spec:
  schedulerName: fluence
  parallelism: 6
  completions: 6
  template:
    metadata:
      labels:
        app: fluence-pi
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          requests:
            cpu: 1
      restartPolicy: Never
