apiVersion: v1
kind: Namespace
metadata:
  name: operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: flux-operator-catalog
  namespace: operator-system
spec:
  sourceType: grpc
  image: ghcr.io/flux-framework/flux-operator-catalog:v0.0.1
  displayName: Flux Operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: flux-operator
  namespace: operator-system
spec:
  channel: alpha
  name: operator
  source: flux-operator-catalog
  sourceNamespace: operator-system
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: flux-operator
  namespace: operator-system

