name: Build Slurm Container Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image - munge
      run: |
        docker build slurm/images/munge --tag ghcr.io/${{ github.actor }}/munge:latest
        docker push ghcr.io/${{ github.actor }}/munge:latest

    - name: Build image - slurm
      run: |
        docker build slurm/images/slurm --tag ghcr.io/${{ github.actor }}/slurm:latest
        docker push ghcr.io/${{ github.actor }}/slurm:latest

    - name: Build image - login
      run: |
        docker build slurm/images/login --tag ghcr.io/${{ github.actor }}/login:latest
        docker push ghcr.io/${{ github.actor }}/login:latest
